version: "3"
services:

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"


  ex:
    image: exspider
    restart: always
    build: .
    command: ./docker-entrypoint.sh storekeeper_prod1 pair_price_alarm_prod
    volumes:
      - .:/opt/exspider
      - /opt/logs:/opt/logs:rw
      - /opt/db:/opt/db:rw
      - /dev/log:/dev/log:rw
    container_name: exspider
    links:
      - redis
    privileged: true
